### PR TITLE
Make usable without Pry loaded

### PR DESCRIPTION
**Pull request by joallard**
For instance if I'm bisecting a gem that doesn't have Pry in it, running a new bundle every time can get annoying. Now it's not exactly easy to get Debundle without Pry.

I'm putting this out there for feedback.

### CODE REVIEW

**Comment by joallard** [comment]
I'll also mention that hard copying debundle.rb as we know is a little bad on updates, we could either suggest what I've PR'd, or suggest maintaining a local copy of the repo?

**Comment by joallard** [comment]
Second commit with more encapsulation goodness!

**Comment by axelson** [comment]
Is it possible for this to get merged? Would be nice when working on random gems.

**Comment by ConradIrwin** [comment]
@axelson Please publish a standalone `debundle` gem (all my code is free to re-use under MIT, so go wild!). I'd happily take a pull request that makes `pry-debundle` depend on that.

**Comment by joallard** [comment]
Sounds reasonable.

**Pull request closed without merging**
